[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.16",
    "discord-py>=2.5.2",
    "python-ffmpeg>=2.0.12",
    "yt-dlp>=2025.4.30",
]
